FROM apache/airflow:slim-3.1.8-python3.11

RUN pip install --no-cache-dir \
    apache-airflow-providers-postgres==6.6.2 \
    apache-airflow-providers-docker==3.14.0 \
    apache-airflow-providers-fab==3.6.0 \
    authlib==1.6.9
