- MLOPS:
    - Jupyter Lab:
        href: http://localhost:8888
        description: Notebooks
        icon: jupyter.png
        widget:
          type: docker
          container: jupyter
          server: my-docker
          stats: true

    - MLflow:
        href: http://localhost:5000
        description: Experiment tracking
        icon: si-mlflow
        widget:
          type: docker
          container: mlflow
          server: my-docker
          stats: true

    - Airflow:
        href: https://airflow.app.localhost
        description: Pipeline orchestration
        icon: apache-airflow.png
        widget:
          type: docker
          container: airflow-webserver
          server: my-docker
          stats: true

    # - LocalStack:
    #     href: http://localhost:4566/health
    #     description: AWS mock
    #     icon: aws.png
    #     widget:
    #       type: docker
    #       container: localstack
    #       server: my-docker
    #       stats: true

- OBSERVABILITY:
    - Prometheus:
        href: http://localhost:9090
        description: Metrics collection
        icon: si-prometheus
        widget:
          type: docker
          container: prometheus
          server: my-docker
          stats: true

    - Grafana:
        href: https://grafana.app.localhost
        description: Dashboards & visualization
        icon: si-grafana
        widget:
          type: docker
          container: grafana
          server: my-docker
          stats: true

    - cAdvisor:
        href: http://localhost:8085
        description: Container metrics
        icon: si-googlecloud
        widget:
          type: docker
          container: cadvisor
          server: my-docker
          stats: true

- MANAGEMENT:
    - Adminer:
        href: http://localhost:8082
        description: Postgres UI
        icon: adminer.png
        widget:
          type: docker
          container: adminer
          server: my-docker
          stats: true

    - Portainer:
        href: https://portainer.app.localhost
        description: Container manager
        icon: portainer.png
        widget:
          type: docker
          container: portainer
          server: my-docker
          stats: true

    - Authelia:
        href: https://auth.app.localhost
        description: SSO Portal
        icon: authelia.png
        widget:
          type: docker
          container: authelia
          server: my-docker
          stats: true
